### ISSUE TITLE
Open grid-ios.xcworkspace in Xcode or build from command line:  xcodebuild -workspace 'grid-ios.xcworkspace' -scheme grid-ios build

### ISSUE THREAD

**Issue by hbsagen** [ngageoint/grid-ios#1]
**Describe the documentation issue**
I am trying to follow the following steps:

Open grid-ios.xcworkspace in Xcode or build from command line:
  xcodebuild -workspace 'grid-ios.xcworkspace' -scheme grid-ios build

But there is no grid-ios.xcworkspace provided

**Comment by danielbarela** [comment]
Did you pod install first?

**Comment by hbsagen** [comment]
I did not. I did work after running pod install.

But can I add it to my project without using pod further? Pod doesn't agree with my Xcode_beta.

**Comment by danielbarela** [comment]
cocoapods is what we currently support.
